<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BrandService.Application/BrandService.Application.csproj" />
    <ProjectReference Include="../BrandService.Infrastructure/BrandService.Infrastructure.csproj" />
  </ItemGroup>
</Project>
